export const SET_TOKEN = 'SET_TOKEN'
export const REMOVE_TOKEN = 'REMOVE_TOKEN'           
export const SET_USERID = 'SET_USERID'  
export const SET_PRODUCT = 'SET_PRODUCT'  
export const REMOVE_USERID = 'REMOVE_USERID'                  